return {
	-- "romgrk/barbar.nvim",
	-- dependencies = {
	-- 	-- "lewis6991/gitsigns.nvim",
	-- 	"nvim-tree/nvim-web-devicons",
	-- },
	-- init = function()
	-- 	vim.g.barbar_auto_setup = false
	-- end,
	-- config = function()
	-- 	require("barbar").setup({
	-- 		animation = false,
	-- 		auto_hide = false,
	-- 		tabpages = true,
	-- 		clickable = true,
	-- 		sidebar_filetypes = {
	-- 			NvimTree = true,
	-- 			undotree = {
	-- 				text = "undotree",
	-- 				align = "center",
	-- 			},
	-- 			Outline = { event = "BufWinLeave", text = "symbols-outline", align = "right" },
	-- 		},
	-- 	})
	-- 	local keymap = require("vim.keymap")
	-- 	print(keymap)
	-- 	keymap.set(
	-- 		"n",
	-- 		"<S-l>",
	-- 		"<CMD>BufferNext<CR>",
	-- 		{ desc = "Move to left tab buffer", noremap = true, silent = true }
	-- 	)
	-- 	keymap.set(
	-- 		"n",
	-- 		"<S-h>",
	-- 		"<CMD>BufferPrevious<CR>",
	-- 		{ desc = "Move to right tab buffer", noremap = true, silent = true }
	-- 	)
	-- end,
	-- version = "^1.0.0",
}
