return {
  -- "Jezda1337/nvim-html-css",
  -- file_extensions = { "css", "sass", "less" },
  -- dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-lua/plenary.nvim" },
  -- config = function()
  --   local cmp  = require("cmp")
  --   local cmp_config = cmp.get_config()
  --
  --   local html_css_source = {
  --     name = "html-css",
  --     option = {
  --       enable_on = { "html", "gotexttmpl"  },
  --       file_extensions = { "tmpl", "css", "sass", "less" },
  --       style_sheets = {
  --         "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
  --       },
  --     },
  --   }
  --   table.insert(cmp_config.sources , html_css_source)
  --   cmp.setup(cmp_config)
  --
  --
  --   require("html-css"):setup()
  --
  -- end,
}
