return {
	-- "roobert/search-replace.nvim",
	-- config = function()
	-- 	require("search-replace").setup({
	-- 		-- optionally override defaults
	-- 		default_replace_single_buffer_options = "gcI",
	-- 		default_replace_multi_buffer_options = "egcI",
	-- 	})
	--
	-- 	local opts = {}
	-- 	vim.api.nvim_set_keymap("v", "<leader>r", "<CMD>SearchReplaceSingleBufferVisualSelection<CR>", opts)
	-- 	vim.api.nvim_set_keymap("v", "<leader>s", "<CMD>SearchReplaceWithinVisualSelection<CR>", opts)
	-- 	vim.api.nvim_set_keymap("v", "<leader>b", "<CMD>SearchReplaceWithinVisualSelectionCWord<CR>", opts)
	--
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rs", "<CMD>SearchReplaceSingleBufferSelections<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>ro", "<CMD>SearchReplaceSingleBufferOpen<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rw", "<CMD>SearchReplaceSingleBufferCWord<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rW", "<CMD>SearchReplaceSingleBufferCWORD<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>re", "<CMD>SearchReplaceSingleBufferCExpr<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rf", "<CMD>SearchReplaceSingleBufferCFile<CR>", opts)
	-- 	--
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rbs", "<CMD>SearchReplaceMultiBufferSelections<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rbo", "<CMD>SearchReplaceMultiBufferOpen<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rbw", "<CMD>SearchReplaceMultiBufferCWord<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rbW", "<CMD>SearchReplaceMultiBufferCWORD<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rbe", "<CMD>SearchReplaceMultiBufferCExpr<CR>", opts)
	-- 	-- vim.api.nvim_set_keymap("n", "<leader>rbf", "<CMD>SearchReplaceMultiBufferCFile<CR>", opts)
	--
	-- 	-- show the effects of a search / replace in a live preview window
	-- 	vim.o.inccommand = "split"
	-- end,
}
