return {
  -- #NOTE use this when you use 9.5
	-- "AckslD/swenv.nvim",
	-- config = function()
	-- 	require("swenv").setup({
	-- 		-- Should return a list of tables with a `name` and a `path` entry each.
	-- 		-- Gets the argument `venvs_path` set below.
	-- 		-- By default just lists the entries in `venvs_path`.
	-- 		get_venvs = function(venvs_path)
	-- 			return require("swenv.api").get_venvs(venvs_path)
	-- 		end,
	-- 		-- Path passed to `get_venvs`.
	-- 		venvs_path = vim.fn.expand("~/venvs"),
	-- 		-- Something to do after setting an environment, for example call vim.cmd.LspRestart
	-- 		post_set_venv = nil,
	-- 	})
	--
	-- 	local keymap = vim.keymap -- for conciseness
	-- 	keymap.set(
	-- 		"n",
	-- 		"<leader>ev",
	-- 		":lua require('swenv.api').pick_venv()<CR>",
	-- 		{ desc = "Pick Env Python", noremap = true }
	-- 	)
	-- end,
}
